import type { EidosRuntimeAPI } from "../../shared/index.js";

export type {
  ApprovalMode,
  RuntimeStatus,
  RuntimeHealth,
  ModelId,
  ModelOption,
  ModelListResult,
  ModelReasoning,
  ModelReasoningSelection,
  ModelPresetModel,
  ModelProviderPreset,
  ModelPresetsResult,
  ModelCreateInput,
  ModelUpdateInput,
  Session,
  Project,
  CreateBranchResult,
  ProjectGitContext,
  SessionWorktree,
  GitDiffScope,
  SessionGitFileStat,
  SessionGitStatus,
  SessionGitMutationResult,
  SessionGitDiff,
  SessionGitCommitResult,
  GitRemoteStatus,
  GitFetchResult,
  GitPullResult,
  GitPushResult,
  GitMergeResult,
  GitRebaseResult,
  ReviewComment,
  ReviewCommentCreateInput,
  SessionListResult,
  SessionSnapshot,
  StepResolutionReview,
  DeleteSessionResult,
  Run,
  ContextUsage,
  Item,
  ToolProvenance,
  ToolCall,
  RuntimeNotification,
  ApprovalDecision,
  FileApprovalRequest,
  CommandApprovalRequest,
  ExternalToolApprovalRequest,
  NetworkApprovalRequest,
  ApprovalRequest,
  PluginRecord,
  PluginListResult,
  SkillMetadata,
  SkillDetail,
  SkillRemoval,
  SkillListResult,
  McpServerRecord,
  McpCreateInput,
  McpUpdateInput,
  McpServerRemoval,
  McpListResult,
  ExtensionSnapshot,
  RuntimeEvent,
  EventListResult,
  AppShortcut,
  WorkspaceDirectoryEntry,
  WorkspaceDirectoryListing,
  WorkspaceFilePreview,
  BrowserAnnotation,
  BrowserBounds,
  BrowserPageState,
  ResponseActionState,
  ResponseFeedbackState,
  ResponseFeedbackValue,
  RunRevisionKind,
  RunRevisionState,
  RunRevisionResult,
  ItemFeedbackResult,
} from "../../shared/index.js";

declare global {
  interface Window {
    eidosRuntime: EidosRuntimeAPI;
  }
}
