import type { EidosRuntimeAPI } from "../../shared/index.js";

export type {
  RuntimeStatus,
  RuntimeHealth,
  ModelId,
  ModelOption,
  ModelListResult,
  ModelReasoning,
  ModelPresetModel,
  ModelProviderPreset,
  ModelPresetsResult,
  ModelCreateInput,
  ModelUpdateInput,
  Session,
  ProjectGitContext,
  SessionWorktree,
  GitDiffScope,
  SessionGitStatus,
  SessionGitDiff,
  SessionListResult,
  SessionSnapshot,
  StepResolutionReview,
  DeleteSessionResult,
  Run,
  ContextUsage,
  Item,
  ToolProvenance,
  ToolCall,
  RuntimeNotification,
  ApprovalDecision,
  FileApprovalRequest,
  CommandApprovalRequest,
  ExternalToolApprovalRequest,
  NetworkApprovalRequest,
  ApprovalRequest,
  PluginRecord,
  PluginListResult,
  SkillMetadata,
  SkillListResult,
  McpServerRecord,
  McpListResult,
  ExtensionSnapshot,
  RuntimeEvent,
  EventListResult,
  AppShortcut,
  ResponseActionState,
  ResponseFeedbackState,
  ResponseFeedbackValue,
  RunRevisionKind,
  RunRevisionState,
  RunRevisionResult,
  ItemFeedbackResult,
} from "../../shared/index.js";

declare global {
  interface Window {
    eidosRuntime: EidosRuntimeAPI;
  }
}
