/* Generated by scripts/generate-collaboration-contracts.mjs. Do not edit. */

export type Parentrunid = string | null;
export type Id = string;
export type Taskname = string;
export type Parentrunid1 = string;
export type Sessionid = string;
export type Runid = string;
export type RunStatus =
  | "queued"
  | "running"
  | "waiting_approval"
  | "waiting_input"
  | "waiting_agents"
  | "finalizing"
  | "succeeded"
  | "failed"
  | "stopped"
  | "canceled"
  | "interrupted";
export type Task = string;
export type Result = string | null;
export type Resultitemid = string | null;
export type Errorcode = string | null;
export type Createdat = number;
/**
 * @maxItems 16
 */
export type Agents = AgentSummary[];
export type Id1 = string;
export type Sendersessionid = string;
export type Recipientsessionid = string;
export type Content = string;
export type Createdat1 = number;
/**
 * @maxItems 16
 */
export type Messages = AgentMessage[];
export type Parentrunid2 = string;
export type Agentid = string;

export interface CollaborationContract {
  state: CollaborationState;
  stop: AgentStopRequest;
}
export interface CollaborationState {
  parentRunId?: Parentrunid;
  agents?: Agents;
  messages?: Messages;
}
export interface AgentSummary {
  id: Id;
  taskName: Taskname;
  parentRunId: Parentrunid1;
  sessionId: Sessionid;
  runId: Runid;
  status: RunStatus;
  task: Task;
  result?: Result;
  resultItemId?: Resultitemid;
  errorCode?: Errorcode;
  createdAt: Createdat;
}
export interface AgentMessage {
  id: Id1;
  senderSessionId: Sendersessionid;
  recipientSessionId: Recipientsessionid;
  content: Content;
  createdAt: Createdat1;
}
export interface AgentStopRequest {
  parentRunId: Parentrunid2;
  agentId: Agentid;
}
