/* Generated by scripts/generate-input-contracts.mjs. Do not edit. */

export type Id = string;
export type Kind = "file" | "directory" | "image" | "skill" | "mcp" | "plugin" | "history" | "excerpt";
export type Label = string;
export type Source = string;
export type Sha256 = string;
export type Status = "content" | "location" | "selection";
export type Size = number;
export type Sessionid = string | null;
export type Origin = "selected" | "clipboard";
export type Kind1 = "file" | "directory" | "image" | "skill" | "mcp" | "plugin" | "history" | "excerpt";
export type Source1 = string;
export type Label1 = string | null;
export type Text = string | null;
/**
 * @maxItems 20
 */
export type Itemids = string[];
export type Pluginid = string | null;
export type Startline = number | null;
export type Endline = number | null;
export type Text1 = string;
export type Thumbnail = string | null;
export type Text2 = string;
export type References = InputReference[];
export type Id1 = string;
export type Offset = number;
export type Id2 = string;
export type Data = string;
export type Mimetype = string;
export type Sizebytes = number;
export type Nextoffset = number;
export type Complete = boolean;

export interface InputContract {
  reference: InputReference;
  prepare: InputPrepareRequest;
  preview: InputPreviewResponse;
  draft: DraftResponse;
  read_asset_request: InputReadAssetRequest;
  read_asset_response: InputReadAssetResponse;
}
export interface InputReference {
  id: Id;
  kind: Kind;
  label: Label;
  source: Source;
  sha256: Sha256;
  status: Status;
  size: Size;
}
export interface InputPrepareRequest {
  sessionId?: Sessionid;
  origin?: Origin;
  kind: Kind1;
  source: Source1;
  label?: Label1;
  text?: Text;
  itemIds?: Itemids;
  pluginId?: Pluginid;
  startLine?: Startline;
  endLine?: Endline;
}
export interface InputPreviewResponse {
  reference: InputReference;
  text: Text1;
  thumbnail?: Thumbnail;
}
export interface DraftResponse {
  text: Text2;
  references: References;
}
export interface InputReadAssetRequest {
  id: Id1;
  offset?: Offset;
}
export interface InputReadAssetResponse {
  id: Id2;
  data: Data;
  mimeType: Mimetype;
  sizeBytes: Sizebytes;
  nextOffset: Nextoffset;
  complete: Complete;
}
