/* Generated by scripts/generate-memory-contracts.mjs. Do not edit. */
export const memorySchema = {
  "$defs": {
    "MemoryActionResult": {
      "additionalProperties": false,
      "properties": {
        "operationId": {
          "title": "Operationid",
          "type": "string"
        },
        "status": {
          "enum": [
            "applied",
            "pending",
            "rejected"
          ],
          "title": "Status",
          "type": "string"
        },
        "entryId": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Entryid"
        },
        "revision": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Revision"
        },
        "code": {
          "title": "Code",
          "type": "string"
        }
      },
      "required": [
        "operationId",
        "status",
        "code"
      ],
      "title": "MemoryActionResult",
      "type": "object"
    },
    "MemoryBackfillRequest": {
      "additionalProperties": false,
      "properties": {
        "sessionId": {
          "title": "Sessionid",
          "type": "string"
        },
        "operationId": {
          "title": "Operationid",
          "type": "string"
        }
      },
      "required": [
        "sessionId",
        "operationId"
      ],
      "title": "MemoryBackfillRequest",
      "type": "object"
    },
    "MemoryBackupRequest": {
      "additionalProperties": false,
      "properties": {
        "destination": {
          "maxLength": 4096,
          "minLength": 1,
          "title": "Destination",
          "type": "string"
        }
      },
      "required": [
        "destination"
      ],
      "title": "MemoryBackupRequest",
      "type": "object"
    },
    "MemoryBackupResult": {
      "additionalProperties": false,
      "properties": {
        "saved": {
          "const": true,
          "default": true,
          "title": "Saved",
          "type": "boolean"
        },
        "encrypted": {
          "const": false,
          "default": false,
          "title": "Encrypted",
          "type": "boolean"
        }
      },
      "title": "MemoryBackupResult",
      "type": "object"
    },
    "MemoryEntry": {
      "additionalProperties": false,
      "properties": {
        "id": {
          "title": "Id",
          "type": "string"
        },
        "scopeId": {
          "title": "Scopeid",
          "type": "string"
        },
        "revision": {
          "maximum": 9007199254740991,
          "minimum": -9007199254740991,
          "title": "Revision",
          "type": "integer"
        },
        "kind": {
          "enum": [
            "preference",
            "decision",
            "continuity",
            "experience",
            "event"
          ],
          "title": "Kind",
          "type": "string"
        },
        "status": {
          "enum": [
            "candidate",
            "active",
            "superseded",
            "archived",
            "quarantined",
            "forgotten"
          ],
          "title": "Status",
          "type": "string"
        },
        "title": {
          "title": "Title",
          "type": "string"
        },
        "content": {
          "title": "Content",
          "type": "string"
        },
        "aliases": {
          "items": {
            "type": "string"
          },
          "title": "Aliases",
          "type": "array"
        },
        "evidenceClass": {
          "enum": [
            "explicit_user",
            "observed_verified",
            "repeated_user",
            "inferred"
          ],
          "title": "Evidenceclass",
          "type": "string"
        },
        "evidence": {
          "items": {
            "$ref": "#/$defs/MemoryEvidence"
          },
          "title": "Evidence",
          "type": "array"
        },
        "pinned": {
          "title": "Pinned",
          "type": "boolean"
        },
        "userOwned": {
          "title": "Userowned",
          "type": "boolean"
        },
        "validFrom": {
          "anyOf": [
            {
              "maximum": 9007199254740991,
              "minimum": -9007199254740991,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Validfrom"
        },
        "validTo": {
          "anyOf": [
            {
              "maximum": 9007199254740991,
              "minimum": -9007199254740991,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Validto"
        },
        "createdAt": {
          "maximum": 9007199254740991,
          "minimum": -9007199254740991,
          "title": "Createdat",
          "type": "integer"
        },
        "updatedAt": {
          "maximum": 9007199254740991,
          "minimum": -9007199254740991,
          "title": "Updatedat",
          "type": "integer"
        },
        "lastUsedAt": {
          "anyOf": [
            {
              "maximum": 9007199254740991,
              "minimum": -9007199254740991,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Lastusedat"
        },
        "useCount": {
          "default": 0,
          "maximum": 9007199254740991,
          "minimum": -9007199254740991,
          "title": "Usecount",
          "type": "integer"
        }
      },
      "required": [
        "id",
        "scopeId",
        "revision",
        "kind",
        "status",
        "title",
        "content",
        "aliases",
        "evidenceClass",
        "evidence",
        "pinned",
        "userOwned",
        "createdAt",
        "updatedAt"
      ],
      "title": "MemoryEntry",
      "type": "object"
    },
    "MemoryEvidence": {
      "additionalProperties": false,
      "properties": {
        "itemId": {
          "title": "Itemid",
          "type": "string"
        },
        "sessionId": {
          "title": "Sessionid",
          "type": "string"
        },
        "runId": {
          "title": "Runid",
          "type": "string"
        },
        "itemRevision": {
          "maximum": 9007199254740991,
          "minimum": -9007199254740991,
          "title": "Itemrevision",
          "type": "integer"
        },
        "sourceRevision": {
          "maximum": 9007199254740991,
          "minimum": -9007199254740991,
          "title": "Sourcerevision",
          "type": "integer"
        },
        "evidenceClass": {
          "enum": [
            "explicit_user",
            "observed_verified",
            "repeated_user",
            "inferred"
          ],
          "title": "Evidenceclass",
          "type": "string"
        }
      },
      "required": [
        "itemId",
        "sessionId",
        "runId",
        "itemRevision",
        "sourceRevision",
        "evidenceClass"
      ],
      "title": "MemoryEvidence",
      "type": "object"
    },
    "MemoryExport": {
      "additionalProperties": false,
      "properties": {
        "markdown": {
          "title": "Markdown",
          "type": "string"
        },
        "privacyEpochs": {
          "additionalProperties": {
            "type": "integer"
          },
          "title": "Privacyepochs",
          "type": "object"
        },
        "encrypted": {
          "const": false,
          "default": false,
          "title": "Encrypted",
          "type": "boolean"
        }
      },
      "required": [
        "markdown",
        "privacyEpochs"
      ],
      "title": "MemoryExport",
      "type": "object"
    },
    "MemoryExportRequest": {
      "additionalProperties": false,
      "properties": {
        "sessionId": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Sessionid"
        },
        "scope": {
          "default": "allowed",
          "enum": [
            "current",
            "global",
            "allowed"
          ],
          "title": "Scope",
          "type": "string"
        },
        "query": {
          "default": "",
          "maxLength": 512,
          "title": "Query",
          "type": "string"
        },
        "limit": {
          "default": 50,
          "maximum": 100,
          "minimum": 1,
          "title": "Limit",
          "type": "integer"
        },
        "cursor": {
          "default": 0,
          "minimum": 0,
          "title": "Cursor",
          "type": "integer"
        },
        "includeHistory": {
          "default": false,
          "title": "Includehistory",
          "type": "boolean"
        },
        "validAt": {
          "anyOf": [
            {
              "maximum": 9007199254740991,
              "minimum": -9007199254740991,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Validat"
        }
      },
      "title": "MemoryExportRequest",
      "type": "object"
    },
    "MemoryGetRequest": {
      "additionalProperties": false,
      "properties": {
        "sessionId": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Sessionid"
        },
        "entryId": {
          "title": "Entryid",
          "type": "string"
        },
        "revision": {
          "anyOf": [
            {
              "minimum": 1,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Revision"
        }
      },
      "required": [
        "entryId"
      ],
      "title": "MemoryGetRequest",
      "type": "object"
    },
    "MemoryGetResult": {
      "additionalProperties": false,
      "properties": {
        "entry": {
          "$ref": "#/$defs/MemoryEntry"
        }
      },
      "required": [
        "entry"
      ],
      "title": "MemoryGetResult",
      "type": "object"
    },
    "MemoryJob": {
      "additionalProperties": false,
      "properties": {
        "id": {
          "title": "Id",
          "type": "string"
        },
        "scopeId": {
          "title": "Scopeid",
          "type": "string"
        },
        "sessionId": {
          "title": "Sessionid",
          "type": "string"
        },
        "sourceRevision": {
          "title": "Sourcerevision",
          "type": "integer"
        },
        "kind": {
          "enum": [
            "extract",
            "consolidate"
          ],
          "title": "Kind",
          "type": "string"
        },
        "state": {
          "enum": [
            "queued",
            "running",
            "succeeded",
            "retry_wait",
            "paused_budget",
            "blocked_model",
            "superseded",
            "canceled",
            "failed"
          ],
          "title": "State",
          "type": "string"
        },
        "modelId": {
          "title": "Modelid",
          "type": "string"
        },
        "attempts": {
          "title": "Attempts",
          "type": "integer"
        },
        "notBefore": {
          "maximum": 9007199254740991,
          "minimum": -9007199254740991,
          "title": "Notbefore",
          "type": "integer"
        },
        "errorCode": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Errorcode"
        },
        "tokens": {
          "maximum": 9007199254740991,
          "minimum": -9007199254740991,
          "title": "Tokens",
          "type": "integer"
        },
        "estimatedUsage": {
          "title": "Estimatedusage",
          "type": "boolean"
        }
      },
      "required": [
        "id",
        "scopeId",
        "sessionId",
        "sourceRevision",
        "kind",
        "state",
        "modelId",
        "attempts",
        "notBefore",
        "tokens",
        "estimatedUsage"
      ],
      "title": "MemoryJob",
      "type": "object"
    },
    "MemoryJobRequest": {
      "additionalProperties": false,
      "properties": {
        "sessionId": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Sessionid"
        },
        "jobId": {
          "title": "Jobid",
          "type": "string"
        }
      },
      "required": [
        "jobId"
      ],
      "title": "MemoryJobRequest",
      "type": "object"
    },
    "MemoryManageRequest": {
      "additionalProperties": false,
      "properties": {
        "action": {
          "enum": [
            "correct",
            "forget",
            "pin",
            "unpin",
            "accept",
            "archive"
          ],
          "title": "Action",
          "type": "string"
        },
        "entryId": {
          "maxLength": 256,
          "minLength": 1,
          "title": "Entryid",
          "type": "string"
        },
        "expectedRevision": {
          "maximum": 9007199254740991,
          "minimum": -9007199254740991,
          "title": "Expectedrevision",
          "type": "integer"
        },
        "content": {
          "anyOf": [
            {
              "maxLength": 8192,
              "minLength": 1,
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Content"
        },
        "sessionId": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Sessionid"
        },
        "operationId": {
          "maxLength": 256,
          "minLength": 1,
          "title": "Operationid",
          "type": "string"
        }
      },
      "required": [
        "action",
        "entryId",
        "expectedRevision",
        "operationId"
      ],
      "title": "MemoryManageRequest",
      "type": "object"
    },
    "MemoryReadRequest": {
      "additionalProperties": false,
      "properties": {
        "sessionId": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Sessionid"
        },
        "scope": {
          "default": "allowed",
          "enum": [
            "current",
            "global",
            "allowed"
          ],
          "title": "Scope",
          "type": "string"
        },
        "query": {
          "default": "",
          "maxLength": 512,
          "title": "Query",
          "type": "string"
        },
        "limit": {
          "default": 50,
          "maximum": 100,
          "minimum": 1,
          "title": "Limit",
          "type": "integer"
        },
        "cursor": {
          "default": 0,
          "minimum": 0,
          "title": "Cursor",
          "type": "integer"
        },
        "includeHistory": {
          "default": false,
          "title": "Includehistory",
          "type": "boolean"
        },
        "validAt": {
          "anyOf": [
            {
              "maximum": 9007199254740991,
              "minimum": -9007199254740991,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Validat"
        }
      },
      "title": "MemoryReadRequest",
      "type": "object"
    },
    "MemoryRebuildRequest": {
      "additionalProperties": false,
      "properties": {
        "sessionId": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Sessionid"
        }
      },
      "title": "MemoryRebuildRequest",
      "type": "object"
    },
    "MemoryScope": {
      "additionalProperties": false,
      "properties": {
        "id": {
          "title": "Id",
          "type": "string"
        },
        "kind": {
          "enum": [
            "global",
            "project"
          ],
          "title": "Kind",
          "type": "string"
        },
        "projectId": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Projectid"
        },
        "settings": {
          "$ref": "#/$defs/MemorySettings"
        },
        "privacyEpoch": {
          "maximum": 9007199254740991,
          "minimum": -9007199254740991,
          "title": "Privacyepoch",
          "type": "integer"
        },
        "generation": {
          "maximum": 9007199254740991,
          "minimum": -9007199254740991,
          "title": "Generation",
          "type": "integer"
        }
      },
      "required": [
        "id",
        "kind",
        "settings",
        "privacyEpoch",
        "generation"
      ],
      "title": "MemoryScope",
      "type": "object"
    },
    "MemorySettings": {
      "additionalProperties": false,
      "properties": {
        "useEnabled": {
          "default": true,
          "title": "Useenabled",
          "type": "boolean"
        },
        "generateEnabled": {
          "default": false,
          "title": "Generateenabled",
          "type": "boolean"
        },
        "dailyCallLimit": {
          "default": 20,
          "maximum": 1000,
          "minimum": 0,
          "title": "Dailycalllimit",
          "type": "integer"
        },
        "dailyTokenLimit": {
          "default": 100000,
          "maximum": 10000000,
          "minimum": 0,
          "title": "Dailytokenlimit",
          "type": "integer"
        },
        "debounceSeconds": {
          "default": 300,
          "maximum": 3600,
          "minimum": 0,
          "title": "Debounceseconds",
          "type": "integer"
        }
      },
      "title": "MemorySettings",
      "type": "object"
    },
    "MemorySettingsRequest": {
      "additionalProperties": false,
      "properties": {
        "sessionId": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Sessionid"
        },
        "scope": {
          "default": "global",
          "enum": [
            "current",
            "global"
          ],
          "title": "Scope",
          "type": "string"
        },
        "settings": {
          "$ref": "#/$defs/MemorySettings"
        }
      },
      "required": [
        "settings"
      ],
      "title": "MemorySettingsRequest",
      "type": "object"
    },
    "MemoryState": {
      "additionalProperties": false,
      "properties": {
        "scopes": {
          "items": {
            "$ref": "#/$defs/MemoryScope"
          },
          "title": "Scopes",
          "type": "array"
        },
        "entries": {
          "items": {
            "$ref": "#/$defs/MemoryEntry"
          },
          "title": "Entries",
          "type": "array"
        },
        "jobs": {
          "items": {
            "$ref": "#/$defs/MemoryJob"
          },
          "title": "Jobs",
          "type": "array"
        },
        "temporary": {
          "title": "Temporary",
          "type": "boolean"
        },
        "truncated": {
          "default": false,
          "title": "Truncated",
          "type": "boolean"
        },
        "nextCursor": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Nextcursor"
        },
        "trigramAvailable": {
          "title": "Trigramavailable",
          "type": "boolean"
        }
      },
      "required": [
        "scopes",
        "entries",
        "jobs",
        "temporary",
        "trigramAvailable"
      ],
      "title": "MemoryState",
      "type": "object"
    },
    "MemoryTemporaryRequest": {
      "additionalProperties": false,
      "properties": {
        "sessionId": {
          "title": "Sessionid",
          "type": "string"
        },
        "temporary": {
          "title": "Temporary",
          "type": "boolean"
        }
      },
      "required": [
        "sessionId",
        "temporary"
      ],
      "title": "MemoryTemporaryRequest",
      "type": "object"
    },
    "MemoryWriteRequest": {
      "additionalProperties": false,
      "properties": {
        "content": {
          "maxLength": 8192,
          "minLength": 1,
          "title": "Content",
          "type": "string"
        },
        "title": {
          "default": "",
          "maxLength": 160,
          "title": "Title",
          "type": "string"
        },
        "kind": {
          "default": "preference",
          "enum": [
            "preference",
            "decision",
            "continuity",
            "experience",
            "event"
          ],
          "title": "Kind",
          "type": "string"
        },
        "scope": {
          "default": "current",
          "enum": [
            "current",
            "global"
          ],
          "title": "Scope",
          "type": "string"
        },
        "aliases": {
          "items": {
            "type": "string"
          },
          "maxItems": 12,
          "title": "Aliases",
          "type": "array"
        },
        "sourceItemIds": {
          "items": {
            "type": "string"
          },
          "maxItems": 16,
          "title": "Sourceitemids",
          "type": "array"
        },
        "validFrom": {
          "anyOf": [
            {
              "maximum": 9007199254740991,
              "minimum": -9007199254740991,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Validfrom"
        },
        "validTo": {
          "anyOf": [
            {
              "maximum": 9007199254740991,
              "minimum": -9007199254740991,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Validto"
        },
        "sessionId": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Sessionid"
        },
        "operationId": {
          "maxLength": 256,
          "minLength": 1,
          "title": "Operationid",
          "type": "string"
        }
      },
      "required": [
        "content",
        "operationId"
      ],
      "title": "MemoryWriteRequest",
      "type": "object"
    }
  },
  "additionalProperties": false,
  "properties": {
    "memoryreadrequest": {
      "$ref": "#/$defs/MemoryReadRequest"
    },
    "memorystate": {
      "$ref": "#/$defs/MemoryState"
    },
    "memorygetrequest": {
      "$ref": "#/$defs/MemoryGetRequest"
    },
    "memorygetresult": {
      "$ref": "#/$defs/MemoryGetResult"
    },
    "memorysettingsrequest": {
      "$ref": "#/$defs/MemorySettingsRequest"
    },
    "memorytemporaryrequest": {
      "$ref": "#/$defs/MemoryTemporaryRequest"
    },
    "memorywriterequest": {
      "$ref": "#/$defs/MemoryWriteRequest"
    },
    "memoryactionresult": {
      "$ref": "#/$defs/MemoryActionResult"
    },
    "memorymanagerequest": {
      "$ref": "#/$defs/MemoryManageRequest"
    },
    "memoryexportrequest": {
      "$ref": "#/$defs/MemoryExportRequest"
    },
    "memoryexport": {
      "$ref": "#/$defs/MemoryExport"
    },
    "memorybackuprequest": {
      "$ref": "#/$defs/MemoryBackupRequest"
    },
    "memorybackupresult": {
      "$ref": "#/$defs/MemoryBackupResult"
    },
    "memoryrebuildrequest": {
      "$ref": "#/$defs/MemoryRebuildRequest"
    },
    "memorybackfillrequest": {
      "$ref": "#/$defs/MemoryBackfillRequest"
    },
    "memoryjobrequest": {
      "$ref": "#/$defs/MemoryJobRequest"
    }
  },
  "required": [
    "memoryreadrequest",
    "memorystate",
    "memorygetrequest",
    "memorygetresult",
    "memorysettingsrequest",
    "memorytemporaryrequest",
    "memorywriterequest",
    "memoryactionresult",
    "memorymanagerequest",
    "memoryexportrequest",
    "memoryexport",
    "memorybackuprequest",
    "memorybackupresult",
    "memoryrebuildrequest",
    "memorybackfillrequest",
    "memoryjobrequest"
  ],
  "title": "MemoryContract",
  "type": "object"
};
export const memoryMethodModels = {
  "memory/list": [
    "MemoryReadRequest",
    "MemoryState"
  ],
  "memory/get": [
    "MemoryGetRequest",
    "MemoryGetResult"
  ],
  "memory/settingsUpdate": [
    "MemorySettingsRequest",
    "MemoryState"
  ],
  "memory/temporary": [
    "MemoryTemporaryRequest",
    "MemoryState"
  ],
  "memory/remember": [
    "MemoryWriteRequest",
    "MemoryActionResult"
  ],
  "memory/manage": [
    "MemoryManageRequest",
    "MemoryActionResult"
  ],
  "memory/export": [
    "MemoryExportRequest",
    "MemoryExport"
  ],
  "memory/backup": [
    "MemoryBackupRequest",
    "MemoryBackupResult"
  ],
  "memory/rebuild": [
    "MemoryRebuildRequest",
    "MemoryState"
  ],
  "memory/backfill": [
    "MemoryBackfillRequest",
    "MemoryState"
  ],
  "memory/jobsRetry": [
    "MemoryJobRequest",
    "MemoryState"
  ]
} as const;
