/* Generated by scripts/generate-memory-contracts.mjs. Do not edit. */

export type Sessionid = string | null;
export type Scope = "current" | "global" | "allowed";
export type Query = string;
export type Limit = number;
export type Cursor = number;
export type Includehistory = boolean;
export type Validat = number | null;
export type Id = string;
export type Kind = "global" | "project";
export type Projectid = string | null;
export type Useenabled = boolean;
export type Generateenabled = boolean;
export type Dailycalllimit = number;
export type Dailytokenlimit = number;
export type Debounceseconds = number;
export type Privacyepoch = number;
export type Generation = number;
export type Scopes = MemoryScope[];
export type Id1 = string;
export type Scopeid = string;
export type Revision = number;
export type Kind1 = "preference" | "decision" | "continuity" | "experience" | "event";
export type Status = "candidate" | "active" | "superseded" | "archived" | "quarantined" | "forgotten";
export type Title = string;
export type Content = string;
export type Aliases = string[];
export type Evidenceclass = "explicit_user" | "observed_verified" | "repeated_user" | "inferred";
export type Itemid = string;
export type Sessionid1 = string;
export type Runid = string;
export type Itemrevision = number;
export type Sourcerevision = number;
export type Evidenceclass1 = "explicit_user" | "observed_verified" | "repeated_user" | "inferred";
export type Evidence = MemoryEvidence[];
export type Pinned = boolean;
export type Userowned = boolean;
export type Validfrom = number | null;
export type Validto = number | null;
export type Createdat = number;
export type Updatedat = number;
export type Lastusedat = number | null;
export type Usecount = number;
export type Entries = MemoryEntry[];
export type Id2 = string;
export type Scopeid1 = string;
export type Sessionid2 = string;
export type Sourcerevision1 = number;
export type Kind2 = "extract" | "consolidate";
export type State =
  | "queued"
  | "running"
  | "succeeded"
  | "retry_wait"
  | "paused_budget"
  | "blocked_model"
  | "superseded"
  | "canceled"
  | "failed";
export type Modelid = string;
export type Attempts = number;
export type Notbefore = number;
export type Errorcode = string | null;
export type Tokens = number;
export type Estimatedusage = boolean;
export type Jobs = MemoryJob[];
export type Temporary = boolean;
export type Truncated = boolean;
export type Nextcursor = number | null;
export type Trigramavailable = boolean;
export type Sessionid3 = string | null;
export type Entryid = string;
export type Revision1 = number | null;
export type Sessionid4 = string | null;
export type Scope1 = "current" | "global";
export type Sessionid5 = string;
export type Temporary1 = boolean;
export type Content1 = string;
export type Title1 = string;
export type Kind3 = "preference" | "decision" | "continuity" | "experience" | "event";
/**
 * Use current for automatic or candidate writes. Global is allowed for those modes only when currentScope is global; otherwise it requires an explicit remember request and authorization.
 */
export type Scope2 = "current" | "global";
/**
 * @maxItems 12
 */
export type Aliases1 = string[];
/**
 * @maxItems 16
 */
export type Sourceitemids = string[];
export type Validfrom1 = number | null;
export type Validto1 = number | null;
/**
 * automatic saves confirmed facts as active; candidate submits a separate pending proposal. Both require the current scope generation setting. remember follows an explicit user save request.
 */
export type Mode = "candidate" | "remember" | "automatic";
/**
 * explicit_user for a clear user statement; observed_verified for successful ordinary tool evidence; inferred requires mode=candidate and stays pending.
 */
export type Evidenceclass2 = "explicit_user" | "observed_verified" | "repeated_user" | "inferred";
/**
 * Existing entry to revise after an explicit factual correction; omit for a new claim.
 */
export type Targetentryid = string | null;
/**
 * Current revision of targetEntryId. Supply both fields together.
 */
export type Expectedrevision = number | null;
export type Sessionid6 = string | null;
export type Operationid = string;
export type Operationid1 = string;
export type Status1 = "applied" | "pending" | "rejected";
export type Entryid1 = string | null;
export type Revision2 = number | null;
export type Code = string;
export type Action = "correct" | "forget" | "pin" | "unpin" | "accept" | "archive";
export type Entryid2 = string;
export type Expectedrevision1 = number;
export type Content2 = string | null;
export type Sessionid7 = string | null;
export type Operationid2 = string;
export type Sessionid8 = string | null;
export type Scope3 = "current" | "global" | "allowed";
export type Query1 = string;
export type Limit1 = number;
export type Cursor1 = number;
export type Includehistory1 = boolean;
export type Validat1 = number | null;
export type Markdown = string;
export type Encrypted = false;
export type Destination = string;
export type Saved = true;
export type Encrypted1 = false;
export type Sessionid9 = string | null;
export type Sessionid10 = string;
export type Operationid3 = string;
export type Sessionid11 = string | null;
export type Jobid = string;

export interface MemoryContract {
  memoryreadrequest: MemoryReadRequest;
  memorystate: MemoryState;
  memorygetrequest: MemoryGetRequest;
  memorygetresult: MemoryGetResult;
  memorysettingsrequest: MemorySettingsRequest;
  memorytemporaryrequest: MemoryTemporaryRequest;
  memorywriterequest: MemoryWriteRequest;
  memoryactionresult: MemoryActionResult;
  memorymanagerequest: MemoryManageRequest;
  memoryexportrequest: MemoryExportRequest;
  memoryexport: MemoryExport;
  memorybackuprequest: MemoryBackupRequest;
  memorybackupresult: MemoryBackupResult;
  memoryrebuildrequest: MemoryRebuildRequest;
  memorybackfillrequest: MemoryBackfillRequest;
  memoryjobrequest: MemoryJobRequest;
}
export interface MemoryReadRequest {
  sessionId?: Sessionid;
  scope?: Scope;
  query?: Query;
  limit?: Limit;
  cursor?: Cursor;
  includeHistory?: Includehistory;
  validAt?: Validat;
}
export interface MemoryState {
  scopes: Scopes;
  entries: Entries;
  jobs: Jobs;
  temporary: Temporary;
  truncated?: Truncated;
  nextCursor?: Nextcursor;
  trigramAvailable: Trigramavailable;
}
export interface MemoryScope {
  id: Id;
  kind: Kind;
  projectId?: Projectid;
  settings: MemorySettings;
  privacyEpoch: Privacyepoch;
  generation: Generation;
}
export interface MemorySettings {
  useEnabled?: Useenabled;
  generateEnabled?: Generateenabled;
  dailyCallLimit?: Dailycalllimit;
  dailyTokenLimit?: Dailytokenlimit;
  debounceSeconds?: Debounceseconds;
}
export interface MemoryEntry {
  id: Id1;
  scopeId: Scopeid;
  revision: Revision;
  kind: Kind1;
  status: Status;
  title: Title;
  content: Content;
  aliases: Aliases;
  evidenceClass: Evidenceclass;
  evidence: Evidence;
  pinned: Pinned;
  userOwned: Userowned;
  validFrom?: Validfrom;
  validTo?: Validto;
  createdAt: Createdat;
  updatedAt: Updatedat;
  lastUsedAt?: Lastusedat;
  useCount?: Usecount;
}
export interface MemoryEvidence {
  itemId: Itemid;
  sessionId: Sessionid1;
  runId: Runid;
  itemRevision: Itemrevision;
  sourceRevision: Sourcerevision;
  evidenceClass: Evidenceclass1;
}
export interface MemoryJob {
  id: Id2;
  scopeId: Scopeid1;
  sessionId: Sessionid2;
  sourceRevision: Sourcerevision1;
  kind: Kind2;
  state: State;
  modelId: Modelid;
  attempts: Attempts;
  notBefore: Notbefore;
  errorCode?: Errorcode;
  tokens: Tokens;
  estimatedUsage: Estimatedusage;
}
export interface MemoryGetRequest {
  sessionId?: Sessionid3;
  entryId: Entryid;
  revision?: Revision1;
}
export interface MemoryGetResult {
  entry: MemoryEntry;
}
export interface MemorySettingsRequest {
  sessionId?: Sessionid4;
  scope?: Scope1;
  settings: MemorySettings;
}
export interface MemoryTemporaryRequest {
  sessionId: Sessionid5;
  temporary: Temporary1;
}
export interface MemoryWriteRequest {
  content: Content1;
  title?: Title1;
  kind?: Kind3;
  scope?: Scope2;
  aliases?: Aliases1;
  sourceItemIds?: Sourceitemids;
  validFrom?: Validfrom1;
  validTo?: Validto1;
  mode?: Mode;
  evidenceClass?: Evidenceclass2;
  targetEntryId?: Targetentryid;
  expectedRevision?: Expectedrevision;
  sessionId?: Sessionid6;
  operationId: Operationid;
}
export interface MemoryActionResult {
  operationId: Operationid1;
  status: Status1;
  entryId?: Entryid1;
  revision?: Revision2;
  code: Code;
}
export interface MemoryManageRequest {
  action: Action;
  entryId: Entryid2;
  expectedRevision: Expectedrevision1;
  content?: Content2;
  sessionId?: Sessionid7;
  operationId: Operationid2;
}
export interface MemoryExportRequest {
  sessionId?: Sessionid8;
  scope?: Scope3;
  query?: Query1;
  limit?: Limit1;
  cursor?: Cursor1;
  includeHistory?: Includehistory1;
  validAt?: Validat1;
}
export interface MemoryExport {
  markdown: Markdown;
  privacyEpochs: Privacyepochs;
  encrypted?: Encrypted;
}
export interface Privacyepochs {
  [k: string]: number;
}
export interface MemoryBackupRequest {
  destination: Destination;
}
export interface MemoryBackupResult {
  saved?: Saved;
  encrypted?: Encrypted1;
}
export interface MemoryRebuildRequest {
  sessionId?: Sessionid9;
}
export interface MemoryBackfillRequest {
  sessionId: Sessionid10;
  operationId: Operationid3;
}
export interface MemoryJobRequest {
  sessionId?: Sessionid11;
  jobId: Jobid;
}
