/* Generated by scripts/generate-memory-contracts.mjs. Do not edit. */
import type * as DTO from "./memory.generated.js";
export interface MemoryMethods {
  "memory/list": {request: DTO.MemoryReadRequest; response: DTO.MemoryState};
  "memory/get": {request: DTO.MemoryGetRequest; response: DTO.MemoryGetResult};
  "memory/settingsUpdate": {request: DTO.MemorySettingsRequest; response: DTO.MemoryState};
  "memory/temporary": {request: DTO.MemoryTemporaryRequest; response: DTO.MemoryState};
  "memory/remember": {request: DTO.MemoryWriteRequest; response: DTO.MemoryActionResult};
  "memory/manage": {request: DTO.MemoryManageRequest; response: DTO.MemoryActionResult};
  "memory/export": {request: DTO.MemoryExportRequest; response: DTO.MemoryExport};
  "memory/backup": {request: DTO.MemoryBackupRequest; response: DTO.MemoryBackupResult};
  "memory/rebuild": {request: DTO.MemoryRebuildRequest; response: DTO.MemoryState};
  "memory/backfill": {request: DTO.MemoryBackfillRequest; response: DTO.MemoryState};
  "memory/jobsRetry": {request: DTO.MemoryJobRequest; response: DTO.MemoryState};
}
