/* Generated by scripts/generate-planning-contracts.mjs. Do not edit. */

export type Id = string;
export type Sessionid = string;
export type Runid = string;
export type Revision = number;
export type Title = string;
export type Markdown = string;
export type Sha256 = string;
export type Status = "draft" | "review" | "accepted";
export type Path = string;
export type Updatedat = number;
export type Executionrunid = string | null;
export type Plans = PlanDocument[];
export type Id1 = string;
export type Sessionid1 = string;
export type Runid1 = string;
export type Itemid = string;
export type Id2 = string;
export type Question = string;
export type Type = "single_select" | "multi_select" | "text";
export type Id3 = string;
export type Label = string;
export type Description = string;
/**
 * @maxItems 6
 */
export type Options = InputOption[];
export type Recommendedoptionid = string | null;
export type Questions1 = InputQuestion[];
export type Status1 = "pending" | "answered" | "skipped" | "canceled";
export type Status2 = "answered" | "skipped";
export type Questionid = string;
/**
 * @maxItems 6
 */
export type Optionids = string[];
export type Text = string;
/**
 * @maxItems 3
 */
export type Answers = InputAnswer[];
export type Createdat = number;
export type Questions = UserInputRequest[];
export type Requestid = string;
export type Planid = string;
export type Expectedrevision = number;
export type Markdown1 = string;
export type Workmode = "execute" | "plan";
export type Planid1 = string | null;
export type Planrevision = number | null;

export interface PlanningContract {
  state: PlanningReadResponse;
  answer: AnswerInputRequest;
  edit: PlanEditRequest;
  run: RunPlanningOptions;
}
export interface PlanningReadResponse {
  plans: Plans;
  questions: Questions;
}
export interface PlanDocument {
  id: Id;
  sessionId: Sessionid;
  runId: Runid;
  revision: Revision;
  title: Title;
  markdown: Markdown;
  sha256: Sha256;
  status: Status;
  path: Path;
  updatedAt: Updatedat;
  executionRunId?: Executionrunid;
}
export interface UserInputRequest {
  id: Id1;
  sessionId: Sessionid1;
  runId: Runid1;
  itemId: Itemid;
  questions: Questions1;
  status: Status1;
  response?: UserInputResponse | null;
  createdAt: Createdat;
}
export interface InputQuestion {
  id: Id2;
  question: Question;
  type?: Type;
  options?: Options;
  recommendedOptionId?: Recommendedoptionid;
}
export interface InputOption {
  id: Id3;
  label: Label;
  description?: Description;
}
export interface UserInputResponse {
  status: Status2;
  answers?: Answers;
}
export interface InputAnswer {
  questionId: Questionid;
  optionIds?: Optionids;
  text?: Text;
}
export interface AnswerInputRequest {
  requestId: Requestid;
  response: UserInputResponse;
}
export interface PlanEditRequest {
  planId: Planid;
  expectedRevision: Expectedrevision;
  markdown: Markdown1;
}
export interface RunPlanningOptions {
  workMode?: Workmode;
  planId?: Planid1;
  planRevision?: Planrevision;
}
