from __future__ import annotations

import os
from pathlib import Path, PurePosixPath
import stat
import time
import uuid

from eidos_runtime.db.database import _prepare_private_directory


class MemoryFiles:
    """Prepare immutable files before publishing their DB reference.

    Caller IDs never become paths. All path components are created and opened
    through directory descriptors; O_NOFOLLOW also applies to parent directories.
    """

    def __init__(self, data_directory: Path) -> None:
        self.root = data_directory / "memory"
        _prepare_private_directory(self.root)

    def _directory(self, parts: tuple[str, ...], *, create: bool = False) -> int:
        fd = os.open(self.root, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
        try:
            for part in parts:
                if not part or part in {".", ".."} or "/" in part:
                    raise ValueError("memory_path_invalid")
                if create:
                    try:
                        os.mkdir(part, 0o700, dir_fd=fd)
                    except FileExistsError:
                        pass
                next_fd = os.open(
                    part, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW, dir_fd=fd
                )
                os.close(fd)
                fd = next_fd
            return fd
        except BaseException:
            os.close(fd)
            raise

    def prepare(self, scope_id: str, content: str) -> str:
        # IDs are generated by the service, never accepted from a tool path.
        uuid.UUID(scope_id)
        raw = content.encode("utf-8")
        if len(raw) > 256 * 1024:
            raise ValueError("memory_body_too_large")
        name = str(uuid.uuid4()) + ".md"
        directory = self._directory(("scopes", scope_id, "revisions"), create=True)
        staging = "." + str(uuid.uuid4())
        try:
            fd = os.open(
                staging,
                os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW,
                0o600,
                dir_fd=directory,
            )
            with os.fdopen(fd, "wb") as stream:
                stream.write(raw)
                stream.flush()
                os.fsync(stream.fileno())
            os.rename(staging, name, src_dir_fd=directory, dst_dir_fd=directory)
            os.fsync(directory)
            return f"scopes/{scope_id}/revisions/{name}"
        finally:
            try:
                os.unlink(staging, dir_fd=directory)
            except FileNotFoundError:
                pass
            os.close(directory)

    def read(self, reference: str) -> str:
        parts = PurePosixPath(reference).parts
        if len(parts) != 4 or parts[0] != "scopes" or parts[2] != "revisions":
            raise ValueError("memory_path_invalid")
        directory = self._directory(parts[:-1])
        try:
            fd = os.open(parts[-1], os.O_RDONLY | os.O_NOFOLLOW, dir_fd=directory)
            with os.fdopen(fd, "rb") as stream:
                before = os.fstat(stream.fileno())
                if (
                    not stat.S_ISREG(before.st_mode)
                    or before.st_nlink != 1
                    or before.st_size > 256 * 1024
                ):
                    raise ValueError("memory_body_invalid")
                body = stream.read(256 * 1024 + 1)
                after = os.fstat(stream.fileno())
                if (before.st_mtime_ns, before.st_size) != (
                    after.st_mtime_ns,
                    after.st_size,
                ):
                    raise ValueError("memory_body_changed")
                return body.decode("utf-8")
        finally:
            os.close(directory)

    def signature(self, reference: str) -> tuple[int, int]:
        parts = PurePosixPath(reference).parts
        if len(parts) != 4 or parts[0] != "scopes" or parts[2] != "revisions":
            raise ValueError("memory_path_invalid")
        directory = self._directory(parts[:-1])
        try:
            fd = os.open(parts[-1], os.O_RDONLY | os.O_NOFOLLOW, dir_fd=directory)
            try:
                value = os.fstat(fd)
                if not stat.S_ISREG(value.st_mode) or value.st_nlink != 1:
                    raise ValueError("memory_body_invalid")
                return value.st_size, value.st_mtime_ns
            finally:
                os.close(fd)
        finally:
            os.close(directory)

    def collect_unreferenced(
        self, referenced: set[str], *, grace_seconds: int = 3600
    ) -> int:
        removed = 0
        scanned = 0
        try:
            scopes = self._directory(("scopes",))
        except FileNotFoundError:
            return 0
        try:
            names = [
                entry.name
                for entry in os.scandir(scopes)
                if entry.is_dir(follow_symlinks=False)
            ]
        finally:
            os.close(scopes)
        for scope in names:
            try:
                uuid.UUID(scope)
                directory = self._directory(("scopes", scope, "revisions"))
            except (OSError, ValueError):
                continue
            try:
                for entry in os.scandir(directory):
                    scanned += 1
                    if scanned > 100000:
                        return removed
                    reference = f"scopes/{scope}/revisions/{entry.name}"
                    if reference in referenced or not entry.is_file(
                        follow_symlinks=False
                    ):
                        continue
                    metadata = entry.stat(follow_symlinks=False)
                    # The grace interval protects the small pre-registration
                    # window of file preparation; age alone never deletes a ref.
                    if metadata.st_mtime > time.time() - grace_seconds:
                        continue
                    os.unlink(entry.name, dir_fd=directory)
                    removed += 1
            finally:
                os.close(directory)
        return removed

    def remove(self, reference: str) -> None:
        parts = PurePosixPath(reference).parts
        if len(parts) != 4 or parts[0] != "scopes" or parts[2] != "revisions":
            raise ValueError("memory_path_invalid")
        directory = self._directory(parts[:-1])
        try:
            try:
                os.unlink(parts[-1], dir_fd=directory)
            except FileNotFoundError:
                pass
        finally:
            os.close(directory)
